### PR TITLE
fix #93

### LINKED ISSUE #93: Truncation Warning for Data Set List Appears at Beginning of Output
**Describe the bug**

If a large list of items are returned by `zowex`, for example, `zowex data-set list` the truncation warning message appears first and users may not be appear that a truncation occurred.  

**Expected and actual results**

Truncation message should appear at the end of the message

**Describe your environment**

**Additional context**

### PR DESCRIPTION
**Pull request by dkelosky**
**What It Does**

**How to Test**

image

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

File: native/c/zowex.cpp [hunk 1]
```diff
@@ -858,27 +858,12 @@ int handle_data_set_list(ZCLIResult result)
...
-        fields.push_back(it->dsorg);
-        fields.push_back(it->volser);
-        std::cout << zut_format_as_csv(fields) << std::endl;
-        fields.clear();
-      }
-      else
-      {
-        std::cout << left << setw(44) << it->name << " " << it->volser << " " << it->dsorg << endl;
-      }
-    }
```
Comment (traeok) [inline native/c/zowex.cpp:876]: quick Q: was this moved elsewhere? just double checking as we'll need the CSV logic for parsing output in the middleware

Comment (dkelosky) [reply native/c/zowex.cpp:876]: lol, this is why we do code reviews... will add this back soon

Comment (dkelosky) [reply native/c/zowex.cpp:876]: ok I'm crazy... it's actually still there if you view the entire file. I had some code duplication which is also fixed by this PR

Comment (traeok) [reply native/c/zowex.cpp:876]: ahh I see - GitHub's diffs are misleading. sorry about that, thanks for clarifying

**Review by traeok — APPROVED** [review]
LGTM, thanks Dan
