### PR TITLE
zut_read_input simplification

### LINKED ISSUE #790: TD: Failing test + printing large amounts of test-data
Failing test:
- "zowex > data-set > write > should write content from a USS file to a sequential data set"
Image

Test printing tons of test-data:
- "zut tests > zut_read_input > should handle large input"
Image

### PR DESCRIPTION
**Pull request by ATorrise**
**What It Does**
Simplifies `zut_read_input` so that all tests pass when running direct through `zowex`  (attached issue shows at least 2 failing tests prior to this change)

now there is no specific handling for line-based TTY input. input is instead read raw which results in data preservation regardless of input type. 

**How to Test**
confirm all tests pass with both methods after building this branch:
- `npm run z:test`
- `<path-to-ur-zowex-build>/c/test: > ./build-out/ztest_runner`

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

File: native/c/zut.cpp [hunk 1]
```diff
@@ -299,14 +303,15 @@ static bool zut_private_command_requires_noshareas(const std::string &command)
...
+static std::string zut_private_get_shell()
+{
   std::string shell_path = "/bin/sh";
 
   // Check if /bin/sh exists AND is executable by the current user
   if (access(shell_path.c_str(), X_OK) != 0)
   {
     // otherwise, try env. If it's empty, we leave shell_path=/bin/sh
-    const char* env_shell = std::getenv("SHELL");
+    const char *env_shell = std::getenv("SHELL");
```
Comment (ATorrise) [inline native/c/zut.cpp:314]: im using vscode in this pr and i think this change is from my editor formatting rules. is this change consequential? should i remove it? and also modify my editor rules so they dont make these types of changes @t1m0thyj

Comment (t1m0thyj) [reply native/c/zut.cpp:314]: I think your formatting rules are good, the changes aren't drastic and my editor does the same thing 👍

File: native/c/zut.cpp [hunk 2]
```diff
@@ -1044,26 +1049,9 @@ FileGuard::operator bool() const
...
-    while (std::getline(input_stream, line))
-    {
-      if (!first_line)
-      {
-        data.push_back('\n');
-      }
-      first_line = false;
-      data += line;
-    }
-  }
```
Comment (zFernand0) [inline native/c/zut.cpp:1066]: TL;DR: I don't recall why we needed this in the first place.

I could be wrong, and others might be able to easily come up with an example where this is absolutely needed

---

<details><summary>Here is what I tried ⬇️  </summary>

I tried things interactively and don't see any issues without this code.

- Piping to `stdin`
``` 
echo "a
b" | zowex ds write HLQ.TEST.PS
```
- Writing directly
```
`zowex ds write HLQ.TEST.PS`
a
b
(ctrl+D)
```

- Passing the same input (`a\nb`) (via server)
```
`zowex server`
{"id": 1, "jsonrpc": "2.0", "method": "writeDataset", "params": {"dsname": "FERNANDO.TEST.PS", "data": "YQpiCg=="}}
```

- Passing 3 newlines (via server)
```
`zowex server`
{"id": 1, "jsonrpc": "2.0", "method": "writeDataset", "params": {"dsname": "FERNANDO.TEST.PS", "data": "CgoK"}}
```

</details>


---

<details><summary>History of events ⬇️ </summary>

**Phase 1**
Back in #751 we attempted to fix something with duplicate newlines.
Personal opinion: The change might've been cosmetic   

**Phase 2**
Moved code from `zowex.cpp` to the individual `commands/[ds|uss].cpp` (see #574)
The code still looked like this (with proper spacing)
`while(getline(context.input_stream(), line) { data +=line; data.push_back('\n'); }`

**Phase 3**
`isatty` check replaced a `hasEncoding` check #124 
I remember reviewing this one, but don't recall exactly why this was done 🤔 

**Phase 4 - Inception**
We were doing this by default since the very beginning.
The code below comes from the first commit in the ZNP project
https://github.com/zowe/zowex/blob/fa01f5327d7856d8e843d01e5be1379046cbe5e6/lib/zowex.cpp#L453-L466

</details>

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
---

All tests passed

Image

I left a comment for other reviewers to consider and perhaps come up with other scenarios that might break this 🙏

File: native/c/zut.cpp (hunk 2 above)
Comment (t1m0thyj) [reply native/c/zut.cpp:1066]: This fix is a cool simplification and I agree - at first I was confused how the new code works, but after research I'm unsure why we needed `std::getline` in the first place 😋 

It seems that reading `stdin` will automatically block until EOF which allows users to input multiple lines until Ctrl+D is pressed, which is same as the old behavior.

This should be standard behavior across shells and more efficient:
Image

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @ATorrise!

File: native/c/zut.cpp (hunk 1 above)
Comment (ATorrise) [reply native/c/zut.cpp:314]: spoke to tim irl and determined it is fine/ok/good that my formatter corrected inconsistencies with this file

**Review by traeok — APPROVED** [review]
LGTM, thanks Amber for the fix
