### PR TITLE
fix: Load dsorg from VTOC instead of calling fopen

### LINKED ISSUE #496: Hang Listing Certain Data Sets
**Describe the bug**

```
bash-4.3$ zowex ds ls sys1.*
08.27.23 STC00084  IEC161I 056-084,DKELOSKY,*OMVSEX,SYS00246,,,SYS1.STGINDEX,  860
   860             IEC161I SYS1.STGINDEX.DATA,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 056-084,DKELOSKY,*OMVSEX,SYS00246,,,SYS1.STGINDEX,  861
   861             IEC161I SYS1.STGINDEX.INDEX,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 062-086,DKELOSKY,*OMVSEX,SYS00246,,,SYS1.STGINDEX,  862
   862             IEC161I SYS1.STGINDEX.DATA,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 056-084,DKELOSKY,*OMVSEX,SYS00247,,,SYS1.STGINDEX,  863
   863             IEC161I SYS1.STGINDEX.DATA,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 062-086,DKELOSKY,*OMVSEX,SYS00247,,,SYS1.STGINDEX,  864
   864             IEC161I SYS1.STGINDEX.DATA,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 056-084,DKELOSKY,*OMVSEX,SYS00248,,,SYS1.STGINDEX,  865
   865             IEC161I SYS1.STGINDEX.INDEX,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEC161I 062-086,DKELOSKY,*OMVSEX,SYS00248,,,SYS1.STGINDEX,  866
   866             IEC161I SYS1.STGINDEX.INDEX,ICF.MASTER.VCATLOG
08.27.23 STC00084  IEF244I DKELOSKY *OMVSEX - UNABLE TO ALLOCATE 1 UNIT(S)  867
   867                     AT LEAST 1 OFFLINE UNIT(S) NEEDED.
08.27.23 STC00084  IEF877E DKELOSKY NEEDS 1 UNIT(S)  868
   868             FOR *OMVSEX SYS00251
   868             FOR VOLUME STGEOS
   868             OFFLINE
   868             0303-0313
   868             : 
   868             OFFLINE, NOT ACCESSIBLE
   868             02E3 0300-0302 0314-0344 0350-037B 2000-20DF 2100-21DF 2200-22DF
   868             2300-23DF 2400-24DF 2500-25DF 2600-26DF 2700-27DF 2800-28DF 2900-29DF
   868             2A00-2ADF 2B00-2BDF 2C00-2CDF 2D00-2DDF 2E00-2EDF 2F00-2FDF 4000
   868             4008-4101 410E-4207 420A-4DFF 4E2B-4EFF 4F2A-4FFF 5100-51DF 5200-52DF
   868             5300-53DF 5400-54DF 5500-55DF 5600-56DF 5700-57DF 5800-58DF 5900-59DF
   868             5A00-5ADF 5B00-5BDF 5C00-5CDF 5D00-5DDF 5E00-5EDF 5F00-5FDF 7400-74DF
   868             7500-75DF 7600-76DF 7700-77DF 7800-78DF 7900-79DF 7A00-7ADF 7B00-7BDF
   868             7C00-7C3F 7D00-7DDF 7E00-7EDF 7F00-7F1F 7F30-7F3F 8400-84DF 8500-85DF
   868             8600-86DF 8700-87DF 8800-88DF 8900-89DF 8B00-8BDF 8C00-8CDF 8D00-8DDF
   868             8E00-8EDF 8F00-8FDF 9400-94A6 9500-95A6 9600-9670 9700-97BF 9800-98DF
   868             9900-99DF 9C00-9CDF 9D00-9DDF 9E00-9EDF 9F00-9FDF A400-A403 A407-A409
   868             A40C-A41F A421-A433 A43A-A449 A450-A45F A46A-A47A A500-A51F A521-A57A
   868             A600-A62C A700-A72C A800-A8DF A900-A9DF AB00-ABDF AC00-ACDF AD00-ADDF
   868             AE00-AEDF AF00-AFDF B900-B9CF BA00-BA0F E202-E207 E209-E20F E218 E26A
   868             E33C-E33D E403-E404 E53C-E53D E63E-E642
   868             : 
08.27.23 STC00084  IEF878I END OF IEF877E FOR DKELOSKY *OMVSEX SYS00251
08.27.23 STC00084 *0003 IEF238D DKELOSKY - REPLY DEVICE NAME OR 'CANCEL'.
```

This command generates `WTOR`s which cannot be responded to and the `zowex` process hangs until a reply is given.  We should understand the environment that causes this behavior and how to avoid unconditionally waiting.  

**Expected and actual results**

**Describe your environment**

**Additional context**

### PR DESCRIPTION
**Pull request by t1m0thyj**
**What It Does**

Fixes #496 where the `zowex ds ls` command could hang when listing data sets that the system cannot open

**How to Test**

Run `./zowex ls ds SYS1.*` on z/OS

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

File: native/c/zdsm.c [hunk 1]
```diff
@@ -95,6 +95,93 @@ typedef int (*IGWASMS)(
...
+  }
+
+  IndexableDSCBFormat1 indexable_dscb = {0};
+  for (int i = 0; i < MAX_DSCBS - 1; i++)
+  {
+    memcpy(&indexable_dscb, workarea + (i * (sizeof(IndexableDSCBFormat1) - 1)), sizeof(indexable_dscb));
+    // The returned DSCB does not include the key, but we can infer the returned variables by re-aligning the struct
+    DSCBFormat1 *dscb = (DSCBFormat1 *)&indexable_dscb;
+
+    // '1' or '8' in EBCDIC
```
Comment (dkelosky) [inline native/c/zdsm.c:149]: what is special about a 1 or 8?

File: native/c/zdsm.c [hunk 2]
```diff
@@ -95,6 +95,93 @@ typedef int (*IGWASMS)(
...
+  // workarea: each DSCB is 140 bytes, we need enough space for format-1 DSCB, format-8 DSCB and max possible format-3 DSCBs (10)
+  // adding 140 bytes for the workarea itself
+  char workarea[sizeof(IndexableDSCBFormat1) * MAX_DSCBS];
+  ObtainParams params = {0};
+
+  // We're using OBTAIN through CAMLST SEARCH to get the DSCBs, see here for more info:
+  // https://www.ibm.com/docs/en/zos/3.1.0?topic=obtain-reading-dscb-by-data-set-name
+
+  // OBTAIN by data set name
+  params.reserved = 0xC1;
```
[the remark this answers is not in the document]
Comment (t1m0thyj) [reply native/c/zdsm.c]: Addressed in https://github.com/zowe/zowe-native-proto/pull/510/commits/60bc90340b6318f41e60f1db9fa3d4c2884e7a6d

File: native/c/zdsm.c (hunk 1 above)
Comment (t1m0thyj) [reply native/c/zdsm.c:148]: I believe we are looking for either a Format-1 and Format-8 DSCB, which are formatted similarly

Comment (t1m0thyj) [reply native/c/zdsm.c]: You are not dense 😋  Addressed in https://github.com/zowe/zowe-native-proto/pull/510/commits/3905fec0efe51a672239082f777ad87e4ca20944

File: native/c/zds.cpp [hunk 3]
```diff
@@ -606,6 +607,95 @@ typedef struct
...
+  if (dsorg->empty())
+  {
+    *dsorg = ZDS_DSORG_UNKNOWN;
+  }
+}
+
+void load_recfm_from_dscb(DSCBFormat1 *dscb, string *recfm)
+{
+  // Bitmasks translated from binary to hex from "DFSMSdfp advanced services" PDF, Chapter 1 page 7 (PDF page 39)
+  *recfm = "";
```
Comment (traeok) [inline native/c/zds.cpp:651]: No need to set as empty string first 😋

File: native/c/zds.cpp [hunk 4]
```diff
@@ -606,6 +607,95 @@ typedef struct
...
+  else if ((dscb->ds1dsorg & 0x0C) == 0x8)
+  {
+    *dsorg = ZDS_DSORG_VSAM;
+  }
+
+  // Unmovable: Last bit of first half is set
+  if (((dscb->ds1dsorg >> 8) & 0x01) == 0x1)
+  {
+    *dsorg += 'U';
+  }
```
Comment (traeok) [inline native/c/zds.cpp:640]: Thoughts on updating the bitmasks to avoid the bit shift?


```suggestion
  // PS: 0100 000x ...
  if ((dscb->ds1dsorg & 0xF000) == 0x4000)
  {
    *dsorg = ZDS_DSORG_PS;
  }
  // DA: 0010 000x ...
  else if ((dscb->ds1dsorg & 0xF000) == 0x2000)
  {
    *dsorg = ZDS_DSORG_DA;
  }
  // PO: 0000 001x ...
  else if ((dscb->ds1dsorg & 0x0E00) == 0x0200)
  {
    *dsorg = ZDS_DSORG_PO;
  }
  // VSAM: ... 000x 10xx
  else if ((dscb->ds1dsorg & 0x0C) == 0x8)
  {
    *dsorg = ZDS_DSORG_VSAM;
  }

  // Unmovable: Last bit of first half is set
  if ((dscb->ds1dsorg & 0x0100) == 0x0100)
  {
    *dsorg += 'U';
  }
```

**Review by traeok — COMMENTED** [review]
Thanks for working on this Timothy! Left a couple suggestions to improve the speed of the bitmasks

**Review by dkelosky — APPROVED** [review]

File: native/c/zds.cpp
[the remark this answers is not in the document]
Comment (dkelosky) [reply native/c/zds.cpp:1]: Let’s see what Trae says, I probably won’t get a chance to look at this today
