### PR TITLE
Timeout Console Requests

### LINKED ISSUE #470: zowex console issue hang when no response
**Describe the bug**

Run `zowex console issue "s ieesysas,prog=iefbr14"` and observer an indefinite hang.

**Expected and actual results**

**Describe your environment**

**Additional context**

### PR DESCRIPTION
**Pull request by dkelosky**
**What It Does**

Fix #470 

FYI @zSeanM 

**How to Test**

**Review Checklist**
I certify that I have:
- [ ] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

**Comment by dkelosky** [comment]
Thank you for confirming!

File: native/c/zowex.cpp [hunk 1]
```diff
@@ -130,6 +130,9 @@ int main(int argc, char *argv[])
                              make_aliases("--wait"),
                              "wait for responses", ArgType_Flag, false,
                              ArgValue(true));
+  issue_cmd->add_keyword_arg("timeout",
```
[the remark this answers is not in the document]
Comment (traeok) [reply native/c/zowex.cpp:133]: It would be nice to support providing a type rather than a default value to ensure proper input. We'll likely need to enhance the parser to support this, I left a comment on #469 with some context

File: native/c/zcnm.c [hunk 2]
```diff
@@ -89,7 +97,13 @@ int ZCNGET(ZCN *zcn, char *response)
   }
 
   if (zcn->ecb)
+  {
+    int timeout = zcn->timeout * 100; // covert milliseconds to seconds
```
Comment (traeok) [inline native/c/zcnm.c:101]: If the intent is to convert ms to sec here, you'll want to use 1,000 as the constant:


```suggestion
    int timeout = zcn->timeout * 1000; // convert milliseconds to seconds
```

File: native/c/zowex.cpp [hunk 3]
```diff
@@ -573,10 +576,16 @@ int handle_console_issue(const ParseResult &result)
   ZCN zcn = {0};
 
   string console_name = result.find_kw_arg_string("console-name");
-  cout << "console name " << console_name << endl;
+  int timeout = result.find_kw_arg_int("timeout");
+
   string command = result.find_pos_arg_string("command");
   bool wait = result.find_kw_arg_bool("wait");
 
+  if (timeout > -1)
```
Comment (traeok) [inline native/c/zowex.cpp:584]: Is a timeout of 0 going to be useful here? Couldn't this cause a command to timeout instantly, even before its finished running?

File: native/c/zcnm.c (hunk 2 above)
Comment (traeok) [reply native/c/zcnm.c]: ah ok, that's odd but fair enough haha 😋  thanks
