### PR TITLE
Fix wildcard

### LINKED ISSUE #947: Wildcard in first dsname qualifier not supported
In Zowe Explorer, searching for `S*.PARMLIB` with a z/OSMF profile will return `SYS1.PARMLIB`, but searching the same pattern with an SSH profile returns nothing.

### PR DESCRIPTION
**Pull request by dkelosky**
**What It Does**

Fixes #947.

This consolidates the parsing of data returned by the CSI so that each record is handled the same (instead of pre-processing catalog entries).

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [x] added/updated automated tests
- [x] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

Worked with @ATorrise

### CODE REVIEW

File: native/c/zds.cpp [hunk 1]
```diff
@@ -3321,7 +3331,7 @@ int zds_list_data_sets(ZDS *zds, std::string dsn, std::vector<ZDSEntry> &dataset
   memset(&selection_criteria->csicldi, 'Y', sizeof(selection_criteria->csicldi));
   memset(&selection_criteria->csiresum, ' ', sizeof(selection_criteria->csiresum));
   memset(&selection_criteria->csicatnm, ' ', sizeof(selection_criteria->csicatnm));
-  memset(&selection_criteria->csis1cat, 'Y', sizeof(selection_criteria->csis1cat)); // do not search master catalog if alias is found
+  memset(&selection_criteria->csis1cat, ' ', sizeof(selection_criteria->csis1cat));
```
Comment (ATorrise) [inline native/c/zds.cpp:3334]: attaching an image of the doc to explain this change
Image
https://www.ibm.com/docs/en/zos/3.2.0?topic=fields-csicatnm-catalog-name

File: native/c/zds.cpp [hunk 2]
```diff
@@ -3363,52 +3370,13 @@ int zds_list_data_sets(ZDS *zds, std::string dsn, std::vector<ZDSEntry> &dataset
...
-
     int work_area_total = csi_work_area->header.used_size;
-    unsigned char *p = (unsigned char *)&csi_work_area->entry;
+    unsigned char *p = (unsigned char *)csi_work_area->catalog;
+    p += (sizeof(ZDS_CSI_CATALOG));
     ZDS_CSI_ENTRY *f = nullptr;
 
     work_area_total -= sizeof(ZDS_CSI_HEADER);
-    work_area_total -= sizeof(ZDS_CSI_CATALOG);
+    work_area_total -= (sizeof(ZDS_CSI_CATALOG));
```
Comment (ATorrise) [inline native/c/zds.cpp]: https://www.ibm.com/docs/en/zos/3.1.0?topic=format-work-area-picture
resetting work area if presence of another catalog

File: native/c/zds.cpp [hunk 3]
```diff
@@ -3449,6 +3451,7 @@ int zds_list_data_sets(ZDS *zds, std::string dsn, std::vector<ZDSEntry> &dataset
           PATH != f->type &&
           ALTERNATE_INDEX != f->type)
       {
+        std::cout << "@TEST address of failed entry is " << (void *)f << std::endl;
```
Comment (t1m0thyj) [inline native/c/zds.cpp]: Test statement should probably be removed.

File: native/CHANGELOG.md [hunk 4]
```diff
@@ -6,6 +6,7 @@ Check [Keep a Changelog](http://keepachangelog.com/) for recommendations on how
 
 ## Recent Changes
 
+- `c`: Fixes wildcard search for listing data sets on multiple catalogs. [#947](https://github.com/zowe/zowex/issues/947)
```
Comment (t1m0thyj) [inline native/CHANGELOG.md:9]: Should we file a separate issue regarding `.**` always being appended to dsn patterns?

**Review by t1m0thyj — APPROVED** [review]
LGTM, thanks @dkelosky and @ATorrise!

Tried a number of different wildcards that failed before, and now they seem to all match z/OSMF behavior 🎉  Noticed that searching for `**.PARMLIB` triggers an error, but this is also true of z/OSMF presumably because the pattern is too loose so I don't think it's a problem.

File: native/CHANGELOG.md (hunk 4 above)
Comment (traeok) [reply native/CHANGELOG.md:9]: In https://github.com/zowe/zowex/pull/185 we added `.**` to resolve the following issue: https://github.com/zowe/zowex/issues/74

See Note 2 under "Query parameters" of the ["List the z/OS data sets on a system"](https://www.ibm.com/docs/en/zos/3.2.0?topic=interface-list-zos-data-sets-system#ListDataSets__QueryParmsForGetListDS__title__1) page: 

> _The system appends the following to any filter criteria that you specify: `.**`_

In order to meet parity w/ z/OSMF, our list data sets functionality should match z/OSMF behavior. Is this actually an issue if z/OSMF also does this, or is this something we're requesting as an enhancement? (something like "exact match" for data set patterns)

Comment (t1m0thyj) [reply native/CHANGELOG.md:9]: I agree that for the majority of cases we want to add `.**` to match z/OSMF. However I believe @dkelosky mentioned some edge cases where adding it may have bad results. Not sure of the details but think it may be if the user already appended `**` or `.**` to the end of their pattern?

Comment (traeok) [reply native/CHANGELOG.md:9]: Ah ok, I should have asked for more context first. Curious to see how z/OSMF behaves with those same patterns, but I agree that we should avoid erroneous list results when possible 😋

File: native/c/zds.cpp (hunk 3 above)
Comment (dkelosky) [reply native/c/zds.cpp]: ah! sorry

File: native/CHANGELOG.md (hunk 4 above)
Comment (dkelosky) [reply native/CHANGELOG.md:9]: yeah, so when I was debugging this with @ATorrise we actually found another bug... in short I thought it was invalid to do something like `s*.**` and have another `.**` appended.  But in reality, one of this multiple wildcard scenarios drove our code down a path where we encountered another bug in the parsing logic.  The case was finding a catalog and data sets that match the pattern, followed by another catalog and more data sets that match the pattern.  

So, in short, I was wrong about the `.**` AND we have much simpler parsing logic now.

Comment (traeok) [reply native/CHANGELOG.md:9]: Ok, sounds like the `.**` can stay and the issue doesn't need filed then?
Thanks for clarifying on the root cause @dkelosky

Comment (dkelosky) [reply native/CHANGELOG.md:9]: correct

**Comment by dkelosky** [comment]
> LGTM, thanks @dkelosky and @ATorrise!
> 
> Tried a number of different wildcards that failed before, and now they seem to all match z/OSMF behavior 🎉 Noticed that searching for `**.PARMLIB` triggers an error, but this is also true of z/OSMF presumably because the pattern is too loose so I don't think it's a problem.

Note that now we properly surface the underlying warning / error condition for this now:

> Error: could not list data set: '**.parmlib.**' rc: '-1'
  Details: IGGCSI00 rc was: '4', rsn was: 'c6e20864'
  
  I'll open this as a low priority on something that can be investigated as a low priority since we achieved parity.

**Review by ATorrise — APPROVED** [review]

**Review by traeok — APPROVED** [review]
