### PR TITLE
Fix auto restore for migrated data sets

### LINKED ISSUE #120: zdsm.c repeatedly called to load/delete iggcsi00
zds.cpp invokes iggcsi00 multiple times for large lists of data sets which incurs the overheard of loading and deleting the module on each call. We should load the module once and delete once after the list operation is complete

### PR DESCRIPTION
**Pull request by dkelosky**
**What It Does**

* fixes link errors
* returns `YES`|`NO` if data set is migrated in zowe explorer UI
* fix #120 
* does not automatically restore data sets when listed

**How to Test**

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [ ] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

### CODE REVIEW

File: native/c/zcli.hpp [hunk 1]
```diff
@@ -526,10 +519,10 @@ int ZCLI::run(int argc, char *argv[])
   }
 
   // attempt to get a group
-  ZCLIGroup &group = get_group(argv[CLI_GROUP_ARG]);
+  ZCLIGroup *group = get_group(argv[CLI_GROUP_ARG]);
 
   // show main help if unknown group
-  if (0 == group.get_verbs().size())
+  if (0 == group->get_verbs().size())
```
Comment (traeok) [inline native/c/zcli.hpp:525]: we should do a `group != nullptr` sanity check before trying `group->get_verbs()`

File: native/c/zowex.cpp [hunk 2]
```diff
@@ -543,10 +543,10 @@ int handle_job_list(ZCLIResult result)
...
   int rc = 0;
   ZJB zjb = {0};
-  string owner_name(result.get_option("--owner").get_value());
-  string prefix_name(result.get_option("--prefix").get_value());
-  string max_entries = result.get_option("--max-entries").get_value();
-  string warn = result.get_option("--warn").get_value();
+  string owner_name(result.get_option("--owner")->get_value());
+  string prefix_name(result.get_option("--prefix")->get_value());
+  string max_entries = result.get_option("--max-entries")->get_value();
+  string warn = result.get_option("--warn")->get_value();
```
Comment (traeok) [inline native/c/zowex.cpp:549]: i think these might cause access violations at runtime if we don't check that option is not `nullptr` first

File: native/c/zcli.hpp (hunk 1 above)
Comment (dkelosky) [reply native/c/zcli.hpp]: fixt

File: native/c/makefile
Comment (zFernand0) [inline native/c/makefile:1]: 🤔 I'm no Makefile expert, but wasn't this added recently 🤯

File: native/c/zcli.hpp [hunk 3]
```diff
@@ -453,55 +446,55 @@ void ZCLI::help()
...
+ZCLIPositional *ZCLIPositionalProvider::get_positional(string positional_name)
 {
   for (vector<ZCLIPositional>::iterator it = positionals.begin(); it != positionals.end(); it++)
   {
     if (positional_name == it->get_name())
-      return *it;
+      return &*it;
   }
-  return ZCLIPositionalProvider::positional_not_found;
+  return nullptr;
```
Comment (zFernand0) [inline native/c/zcli.hpp:497]: thanks for returning the `nullptr` instead.
I believe this is part of the refactoring effort that you and Trae were discussing offline. 🙏

File: native/c/zds.hpp [hunk 4]
```diff
@@ -24,11 +24,15 @@ struct ZDSMem
...
 
+#define MIGRATE_YES "YES"
+#define MIGRATE_NO "NO"
+
 struct ZDSEntry
 {
   std::string name;
   std::string dsorg;
   std::string volser;
+  std::string migr;
```
Comment (zFernand0) [inline native/c/zds.hpp:35]: This makes the DS entry consistent with FTP ([zos-node-accessor](https://github.com/IBM/zos-node-accessor/blob/0431d0d244aee348d71ec7357f2fd17c1b58fc69/src/interfaces/DatasetEntry.ts#L41)) 🥳 

If it's all the same to y'all... could we make this a boolean value? 
Unless we believe that we may want to use it for something other than a `yes|no` value. 😋

File: native/c/zds.cpp [hunk 5]
```diff
@@ -614,8 +625,20 @@ int zds_list_data_sets(ZDS *zds, string dsn, vector<ZDSEntry> &attributes)
           entry.volser = value;
         }
       }
+#define MIGRAT_VOLUME "MIGRAT"
+#define ARCIVE_VOLUME "ARCIVE"
+
+      if (entry.volser == MIGRAT_VOLUME || entry.volser == ARCIVE_VOLUME)
```
Comment (zFernand0) [inline native/c/zds.cpp:630]: I like this implementation 🥳 
This makes it flexible enough to support some third-party mainframe product that uses other conventions for migrating/archiving content. 🙏

File: native/c/zowex.cpp [hunk 6]
```diff
@@ -1040,11 +1040,12 @@ int handle_data_set_restore(ZCLIResult result)
...
   int rc = 0;
-  string dsn = result.get_positional("dsn").get_value();
-  ZCLIOption &encoding = result.get_option("--encoding");
+  string dsn = result.get_positional("dsn")->get_value();
   ZDS zds = {0};
   string response;
-  const auto hasEncoding = result.get_option("--encoding").is_found() && zut_prepare_encoding(result.get_option("--encoding").get_value(), &zds.encoding_opts);
+
+  ZCLIOption *opt = result.get_option("--encoding");
+  const auto hasEncoding = result.get_option("--encoding") && zut_prepare_encoding(result.get_option("--encoding")->get_value(), &zds.encoding_opts);
```
Comment (zFernand0) [inline native/c/zowex.cpp:1048]: Why not reuse the `opt` value? 😋

**Review by zFernand0 — COMMENTED** [review]
Changes LGTM! 😋 
---

I haven't tested it yet, but I left some small comments 😅 
However, I'm not really requesting changes 😋

File: native/c/zowex.cpp [hunk 7]
```diff
@@ -852,8 +852,8 @@ int handle_console_issue(ZCLIResult result)
   int rc = 0;
   ZCN zcn = {0};
 
-  string console_name(result.get_option("--console-name").get_value());
-  string command(result.get_positional("command").get_value());
+  string console_name(result.get_option("--console-name")->get_value());
+  string command(result.get_positional("command")->get_value());
```
Comment (zFernand0) [inline native/c/zowex.cpp:856]: There are a few missed statements in the above function 😋 
`handle_job_cancel`

```cpp
  string jobid(result.get_positional("jobid").get_value());
  string option_dump(result.get_option("--dump").get_value());
  string option_force(result.get_option("--force").get_value());
  string option_purge(result.get_option("--purge").get_value());
  string option_restart(result.get_option("--restart").get_value());
```

**Review by zFernand0 — CHANGES_REQUESTED** [review]
Left a small comment, but this definitely cleans up quite a few of the warnings that showed up 😋 
```
IEW2480W A711 EXTERNAL SYMBOL validate__EI4ZCLIFv OF TYPE LD WAS ALREADY       
          DEFINED AS A SYMBOL OF TYPE LD IN SECTION zowex#C.                    
 IEW2482W A712 THE ORIGINAL DEFINITION WAS IN A MODULE IDENTIFIED BY DDNAME     
          /0000001.  THE DUPLICATE DEFINITION IS IN SECTION zcli#C  IN A        
          MODULE IDENTIFIED BY DDNAME /0000002.                                 
```

I still see the occasional informational message:
`64-bit portability: possible loss of digits through conversion of unsigned long int type into int type.`

File: native/c/zds.hpp (hunk 4 above)
Comment (dkelosky) [reply native/c/zds.hpp:35]: I agree, I'll change this

File: native/c/zowex.cpp (hunk 6 above)
Comment (dkelosky) [reply native/c/zowex.cpp:1048]: bc im a dummy - fix incoming

File: native/c/zowex.cpp (hunk 7 above)
Comment (dkelosky) [reply native/c/zowex.cpp:856]: fixt

File: native/c/zds.hpp (hunk 4 above)
Comment (dkelosky) [reply native/c/zds.hpp]: fixt

**Review by zFernand0 — APPROVED** [review]
LGTM! 😋 
---

Thanks for addressing all the dumb comments 🙏
