### PR TITLE
fix(server): only lock mutex at time of i/o call

### LINKED ISSUE #633: zowed: I/O bottleneck when printing response to error & output streams
**Describe the bug**

The current code uses a single, global `std::mutex response_mutex`, which is locked for the entire duration of the `print_response` function. This includes logging, serializing the JSON to a string, and finally writing it to `std::cout` or `std::cerr`.

**Expected and actual results**

The lock should only be held for the duration when writing the error/output, so that other requests are not held up from serialization or logging done in other threads.

**Additional context**

Only exists on `main` since we haven't released the new middleware yet

### PR DESCRIPTION
**Pull request by traeok**
**What It Does**

Fixes #633 

**How to Test**

Kind of difficult to see the difference unless the worker pool is saturated w/ requests.
May notice a slight increase in speed due to enabling parallelization for JSON serialization and logic before the write to stream

**Review Checklist**
I certify that I have:
- [x] tested my changes
- [ ] added/updated automated tests
- [ ] updated the changelog
- [x] followed the [contribution guidelines](https://github.com/zowe/zowe-cli/blob/master/CONTRIBUTING.md)

**Additional Comments**

No changelog since middleware is not yet released

### CODE REVIEW

File: native/zowed/server.cpp [hunk 1]
```diff
@@ -300,15 +298,10 @@ void RpcServer::print_response(const RpcResponse &response)
...
-  if (response.error.has_value())
-  {
-    std::cerr << json_string << std::endl;
-  }
-  else
+  auto &stream = response.error.has_value() ? std::cerr : std::cout;
   {
-    std::cout << json_string << std::endl;
+    std::lock_guard<std::mutex> lock(response_mutex);
+    stream << json_string << std::endl;
```
Comment (t1m0thyj) [inline native/zowed/server.cpp]: Can the curly braces around these lines be removed?

**Review by t1m0thyj — APPROVED** [review]
This is significantly cleaner than before, thanks @traeok!
